### ISSUE TITLE
Constraints in sfl4j integration are too strong

### ISSUE THREAD

**Issue by kubukoz** [valskalla/odin#170]
Hi! Thanks for the library, it looks really cool and works very well, including the slf4j integration (I'm only starting with it though).

I noticed the constraints the slf4j binder requires are a bit strong: `Timer` and `ConcurrentEffect` are requiested, even though they're only used for `toIO` (`Effect`) and `Clock` (current time). We might as well just pass these, and we wouldn't even need an `ExecutionContext` for the cats-effect 2.x instance.

I'll gladly contribute that if you agree :)

**Comment by sergeykolbasov** [comment]
Hi @kubukoz 

Thanks for the feedback. I agree, and it's an easy fix https://github.com/valskalla/odin/pull/171

Will release 0.8.1 once it's merged

**Comment by sergeykolbasov** [comment]
Done

**Comment by kubukoz** [comment]
Thanks!

**Comment by kubukoz** [comment]
btw. the same applies to Timer in DefaultLogger - we also only need Clock.

Loosening this constraint would be really nice too, as we could get rid of the EC requirement in slf4j completely.

**Comment by sergeykolbasov** [comment]
That is a bit trickier and depends on cats-effect. There was a conflict between deriving `Clock` from `Timer` and the rest of `Clock` implicits for different data types. It was fixed in https://github.com/typelevel/cats-effect/commit/1cbf8ca7fce7f2d907e546d8082c32c461c1a731#diff-8caacbebb3a4edd3e3545d4f79f3ba67

But still waiting for that 2.2 release.
